name: Build and Publish Gentoo Docker Image

on:
  schedule:
    - cron: '20 19 * * *'

env:
  docker_registory: docker.pkg.github.com

jobs:
  build_push_gentoo-amd64:
    name: gentoo-amd64
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "::set-env name=date::$(date +'%Y%m%d')"
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v1.1.0
        env:
          target_image: gentoo/gentoo-amd64
          base_image: gentoo/stage3-amd64
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.docker_registory }}
          repository: ${{ github.repository }}/${{ env.target_name }}
          build_args: base_image=${{ env.base_image }}
          tags: latest, ${{ env.date }}

  build_push_stage3-amd64-systemd:
    name: stage3-amd64-systemd
    runs-on: ubuntu-latest
    env:
      image_name: stage3-amd64-systemd
    outputs:
      image: ${{ env.docker_registory }}/${{ github.repository }}/${{ env.image_name }}
    steps:
      - name: Get current date
        run: echo "::set-env name=date::$(date +'%Y%m%d')"
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository:  gentoo/gentoo-docker-images 
          path: official
          submodules: true
      - name: Build the image
        env:
          TARGET: stage3-amd64-systemd
        run: ./build.sh
        shell: bash
        working-directory: ./official
      - name: Push to GitHub Packages
        env:
          image_id: ${{ env.docker_registory }}/${{ github.repository }}/${{ env.image_name }}
          org: gentoo
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.docker_registory }} -u ${{ github.actor }} --password-stdin
          docker tag ${{ env.org }}/${{ env.image_name }} ${{ env.image_id }}:${{ env.date }}
          docker tag ${{ env.image_id }}:${{ env.date }} ${{env.image_id}}:latest
          docker push ${{ env.image_id }}:${{ env.date }}
          docker push ${{ env.image_id }}:latest
        shell: bash

  build_push_gentoo-amd64-systemd:
    name: gentoo-amd64-systemd
    needs: build_push_stage3-amd64-systemd
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "::set-env name=date::$(date +'%Y%m%d')"
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v1.1.0
        env:
          target_name: gentoo-amd64-systemd
          base_image: ${{ needs.build_push_stage3-amd64-systemd.outputs.image }}
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.docker_registory }}
          repository: ${{ github.repository }}/${{ env.target_name }}
          build_args: base_image=${{ env.base_image }}
          tags: latest, ${{ env.date }}
