name: Build and Publish Gentoo Docker Image

on: release

env:
  docker_registory: docker.pkg.github.com

jobs:
  build_push_gentoo-amd64:
    name: gentoo-amd64
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: pluser/gentoo-docker-build-by-github/gentoo-amd64
          build_args: base_image=gentoo/stage3-amd64:latest
          tag_with_ref: true

  build_push_stage3-amd64-systemd:
    name: stage3-amd64-systemd
    runs-on: ubuntu-latest
    env:
      image_name: stage3-amd64-systemd
    outputs:
      image_name: ${{ env.image_name }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository:  gentoo/gentoo-docker-images 
          path: official
          submodules: true
      - name: Build the image
        env:
          TARGET: stage3-amd64-systemd
        run: ./build.sh
        shell: bash
        working-directory: ./official
      - name: Push to GitHub Packages
        env:
          image_id: ${{ env.docker_registory }}/${{ github.repository }}/${{ env.image_name }}
          org: gentoo
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.docker_registory }} -u ${{ github.actor }} --password-stdin
          docker tag ${{ env.org }}/${{ env.image_name }} ${{ env.docker_registory }}/${{ github.repository }}/${{ env.image_name }}:latest
          docker push ${{ env.image_id }}:latest
        shell: bash

  build_push_gentoo-amd64-systemd:
    name: gentoo-am64-systemd
    needs: build_push_stage3-amd64-systemd
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1.1.0
        env:
          target_name: gentoo-amd64-systemd
          base_name: ${{ needs.build_push_stage3-amd64-systemd.outputs.image_name }}
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.docker_registory }}
          repository: ${{ github.repository }}/${{ env.target_name }}
          build_args: base_image=/${{ github.repository }}/${{ env.base_name }}
          tag_with_ref: true
